# object information
# Choose from: foldingchair, refrigerator, laptop, oven, scissor, stapler, usb, 
#              washer, knife, storage, storage-2, refrigerator-2, storage-3
object_class: storage       # Object class name to visualize

# articulation
joint_angle: 0.2            # Set all joint angles to this value

# camera information
camera_info:
  view_name: full_48        # Name of predefined camera view configuration
  radius: 1.0               # Distance from the camera to the object center
  num_phi: 4                # Number of vertical angles (elevation samples)
  phi_range: [10.0, 60.0]   # Range of elevation angles (in degrees)
  num_theta: 12             # Number of horizontal angles (azimuth samples)
  theta_range: [-180.0, 180.0] # Range of azimuth angles (in degrees)